#!/usr/bin/env python
import re
import sys 
from sploitkit import *
from tinyscript.helpers import is_bool, ExpiringDict, Path
from tinyscript import *

class OINTS(FrameworkConsole):
    exclude = ["root/test", "root/help"]
    sources = {'banners': "banners"}
    
__all__ = ["OINTS"]
__script__ = "OINTS"
__doc__    = """
Launches OINTS!
"""

if __name__ == '__main__':
    parser.add_argument("-d", "--dev", action="store_true", help="enable development mode")
    initialize(exit_at_interrupt=False)
    
    #add traceback   
    sys.tracebacklimit=0

    sys.dont_write_bytecode = True

    c = OINTS(
        "OINTS",
        #TODO: configure your console settings
        banner_section_styles={'title': {'fgcolor': "lolcat"}},
        dev=args.dev,
        debug=args.verbose,
    )
    c.start()
